### ISSUE TITLE
Game crashes when resetting to default biters

### ISSUE THREAD

**Issue by vavavr00m** [heyqule/enemy_race_manager#34]
I only use ERM to delete biters and modify the evolution factor (while other players are using terran units but no other ERM enemies are installed) but somehow the corrupted stuff keep coming back after resetting and then pressing the reset to default biters crashes the game. Non-QoL mods are Space Exploration and Rampant Evolution.

**Comment by heyqule** [comment]
What's the error message?  May you please send me a link to your save as well?

**Comment by heyqule** [comment]
It didn't crash on my end.  The reset process took 4 minutes to complete on my computer.   

The reset process freeze the game to run with all available resource. It also prevents unwanted enemies from spawning during the reset process since the whole process ran within the same game tick.  Since you mentioned "Server is not responding.".  I guess that's the issue.  I'll re-word the tooltip in next release.

Regarding to the corrupted stuff keep coming back,  are you talking about the corrupted aerial robots?   I can add a setting to disable them in next release.  But you would be OP if you have aerial units from ERM Terran and the enemies don't aerial units.

**Comment by vavavr00m** [comment]
> It didn't crash on my end. The reset process took 4 minutes to complete on my computer.

> The reset process freeze the game to run with all available resource. It also prevents unwanted enemies from spawning during the reset process since the whole process ran within the same game tick. Since you mentioned "Server is not responding.". I guess that's the issue. I'll re-word the tooltip in next release.

Woah that's long. Is it normal that the players are dropped from the server and unable to reconnect while it's processing? It wasn't like that at first - it was just a quick wipe and nobody got dropped.

> Regarding to the corrupted stuff keep coming back, are you talking about the corrupted aerial robots? I can add a setting to disable them in next release. But you would be OP if you have aerial units from ERM Terran and the enemies don't aerial units.

Yes, any corrupted (aerial units, spawners) as we only wanted the vanilla ones but like the ERM GUI to manage the biters. The reason the ERM Terran units were added was because of the corrupted aerial units making their way inside the base easily. Additionally, it felt like with ERM installed, the biters were scaling the walls (I've seen this), tunneling in or getting spawned in by the corrupted units (I've also seen this happen but uncertain what really was happening) because they keep getting inside and wreaking havoc without breaking the walls.

Rather than a setting disabling them altogether, I would suggest different buttons to disable specific actions per enemy (biters tunneling and/or scaling if those have been added by ERM, and aerial units acting like a spawner?) since ERM is currently being used only to control the evolution factor for now.

In relation to evolution factor, what is the compatibility of ERM with [Rampant Evolution](https://mods.factorio.com/mod/RampantEvolution)? Will it be made compatible in the future if it isn't yet? Would be cool to be able to set different evolution parameters per enemy. Currently, when ERM is used to set the evolution factor, Rampant Evolution calculations go bonkers and sometimes doesn't respect the level ERM set (for example, ERM set it to 1%, Rampant Evolution then recalculates it to 90%)

**Comment by heyqule** [comment]
The reset process is never designed to work with multiplayer or in mid-game.  It's for when you want to uninstall my enemy mods and revert my custom enemies back to default enemies.  

Early game doesn't have that problem because you don't have too many explored chunks.  Reset process only resets what's already on the map.  Newly explored units still follow the ERM rules.

ERM designed as hardcore base defense.  It's never intended to be use as an UI tool.  What you see are the new features from ERM.  For biters, ERM adds 3 new types of aerial robots.    Attack robots, units dropping robots and proxy spawner building robots.  Wall is useless against aerial, you need to have solid defense to hunt all enemies down before they wreck your base.  This mod requires players to think about the defense strategies.  It's not like base game, it's a walk in the park.   Using only one type of turret after early-game will not properly defense your base.   You will also need to have an automated repairing network set up ASAP as well.

> I would suggest different buttons to disable specific actions per enemy

It will take significant amount of work to tweak the aerial workflow.  I don't have intension to make it easier.

> (for example, ERM set it to 1%, Rampant Evolution then recalculates it to 90%)  

This is not a fixable conflict.  There is no way to fix this when two mods are trying to set the same value based in its workflow.  Periodic automatic calculation will always override the manual entry.
